// This file is generated by Aerox dynamically while building
#pragma once
#ifndef COMPONENTS_HPP
#define COMPONENTS_HPP
#include <iostream>
#include "metadata.hpp"
using namespace std;

string MainRoot(string children);

string Header();

string Footer();

#endif

