// This file is generated by Aerox dynamically while building
#include "pages.hpp"
#include "components.hpp"
static unordered_map<string, function<void(Request, Response)>> pages;
static void initRenders(){
	pages["/posts"] = [](Request req, Response res){
		string page = Posts(req);
		string root = MainRoot(page);
		res.send(root);
__title__ = "";
__description__ = "";
	};

	pages["/"] = [](Request req, Response res){
		string page = Index(req);
		string root = MainRoot(page);
		res.send(root);
__title__ = "";
__description__ = "";
	};

	pages["/contact"] = [](Request req, Response res){
		string page = Contact(req);
		string root = MainRoot(page);
		res.send(root);
__title__ = "";
__description__ = "";
	};

	pages["/post/[id]"] = [](Request req, Response res){
		string page = SinglePost(req);
		string root = MainRoot(page);
		res.send(root);
__title__ = "";
__description__ = "";
	};

	pages["/about"] = [](Request req, Response res){
		string page = About(req);
		string root = MainRoot(page);
		res.send(root);
__title__ = "";
__description__ = "";
	};

}

