// This file is generated by Aerox dynamically while building
#include "pages.hpp"
#include "components.hpp"
#include "../ext/json.hpp"
static unordered_map<string, function<void(Request, Response)>> pages;
static string sendNavigationResponse(string page){
	nlohmann::json data;
	data["body"] = page;
	nlohmann::json meta;
	meta["title"] = __title__;
	meta["description"] = __description__;
	data["meta"] = meta;
	return data.dump();
}
static void initRenders(){
	pages["/posts"] = [](Request req, Response res){
		string page = Posts(req);
		string root = MainRoot(page);
		if (req.query["navigate"] != "")
			res.sendJSON(sendNavigationResponse(page));
		else
			res.send(root);
	__title__ = "";
	__description__ = "";
	};

	pages["/"] = [](Request req, Response res){
		string page = Index(req);
		string root = MainRoot(page);
		if (req.query["navigate"] != "")
			res.sendJSON(sendNavigationResponse(page));
		else
			res.send(root);
	__title__ = "";
	__description__ = "";
	};

	pages["/contact"] = [](Request req, Response res){
		string page = Contact(req);
		string root = MainRoot(page);
		if (req.query["navigate"] != "")
			res.sendJSON(sendNavigationResponse(page));
		else
			res.send(root);
	__title__ = "";
	__description__ = "";
	};

	pages["/post/[id]"] = [](Request req, Response res){
		string page = SinglePost(req);
		string root = MainRoot(page);
		if (req.query["navigate"] != "")
			res.sendJSON(sendNavigationResponse(page));
		else
			res.send(root);
	__title__ = "";
	__description__ = "";
	};

	pages["/about"] = [](Request req, Response res){
		string page = About(req);
		string root = MainRoot(page);
		if (req.query["navigate"] != "")
			res.sendJSON(sendNavigationResponse(page));
		else
			res.send(root);
	__title__ = "";
	__description__ = "";
	};

	pages["/posts"] = [](Request req, Response res){
		string page = Posts(req);
		string root = MainRoot(page);
		if (req.query["navigate"] != "")
			res.sendJSON(sendNavigationResponse(page));
		else
			res.send(root);
	__title__ = "";
	__description__ = "";
	};

	pages["/"] = [](Request req, Response res){
		string page = Contact(req);
		string root = MainRoot(page);
		if (req.query["navigate"] != "")
			res.sendJSON(sendNavigationResponse(page));
		else
			res.send(root);
	__title__ = "";
	__description__ = "";
	};

	pages["/contact"] = [](Request req, Response res){
		string page = SinglePost(req);
		string root = MainRoot(page);
		if (req.query["navigate"] != "")
			res.sendJSON(sendNavigationResponse(page));
		else
			res.send(root);
	__title__ = "";
	__description__ = "";
	};

	pages["/post/[id]"] = [](Request req, Response res){
		string page = About(req);
		string root = MainRoot(page);
		if (req.query["navigate"] != "")
			res.sendJSON(sendNavigationResponse(page));
		else
			res.send(root);
	__title__ = "";
	__description__ = "";
	};

}

